Feature patient query
wichopy/fhir-graphql pull request #14
Opened 2019-01-18 03:45 UTC by ronniemara

Resolves #9

2019-01-19 04:44 UTC, wichopy requested changes
A few syntax errors to fix.

2019-01-19 04:44 UTC, wichopy commented on resolvers.js
> +	    console.log(res)
Can remove this.

2019-01-19 04:44 UTC, wichopy commented on resolvers.js
> +    };
The linter is showing some syntax errors, looks like this should be a big object.

<img width="580" alt="screen shot 2019-01-18 at 11 43 32 pm" src="https://user-images.githubusercontent.com/24414632/51422337-ef85e380-1b7a-11e9-951b-ddc06c63f16f.png">

2019-01-20 15:32 UTC, wichopy commented on src/resolvers.js
> +    };
I think you are also missing an extra `}` here. Did you try running it locally?

2019-01-21 00:31 UTC, ronniemara commented
@wichopy I added airbnb styleguide to this branch. The style guide is causing some errors and warnings during linting. Can you checkout this branch and fix the liniting errors and warnings?

2019-01-21 01:09 UTC, wichopy commented
Added fixes. Should run now when you run `npm run start`

2019-01-21 18:21 UTC, merged